### ISSUE TITLE
[Bug] What's the real_data_ratio to hopper and walker2d?

### ISSUE THREAD

**Issue by chenxi-yang** [facebookresearch/mbrl-lib#167]
Hi I can not make hopper and walker2d work in this default setting. May I ask if you set a >0 real_data_ratio to these two experiments? Thanks!

**Comment by luisenp** [comment]
Hi @chenxi-yang, thanks for the report. Can you be more explicit on the errors you are getting? Is it not learning at all, or is it that the reward less than you expect? I don't think I've ever used `real_data > 0`.

**Comment by luisenp** [comment]
Ah, got it. Unfortunately, the peaky behavior is definitely an issue for our MBPO implementation; certainly it is for Hopper, but I think also for other domains. Not sure if this is the cause, but when I swept for hyperparameters, I roughly optimized for area under curve on a single seed, rather than stable behavior. So, it's possible that this could be addressed by tweaking hyperparameters, but I haven't looked into this.

**Comment by chenxi-yang** [comment]
Thanks for the update.
