### ISSUE TITLE
Implement iCEM

### ISSUE THREAD

**Issue by luisenp** [facebookresearch/mbrl-lib#23]
There is a newer version of CEM that uses colored noise, which is correlated in time. [This](https://arxiv.org/pdf/2008.06389.pdf) paper describes the method, along with several additional improvements. Having this as a new agent (or a modified version of CEMAgent) would be a great addition.

**Comment by sradicwebster** [comment]
Hi @luisenp. I have been working on an implementation of iCEM but have run into an issue when using GaussianMLP ensembles. iCEM uses a decaying population size, but this results in the population batch size to not be a multiple of the number of models in the ensemble. What's the reason for the batch size to be a multiple of ensemble size? Can you think of a workaround? Thanks

**Comment by luisenp** [comment]
Hi @sradicwebster, thanks for the interest! The reason for this restriction is due to an optimization in the ensemble propagation of GaussianMLP, as described [here](https://github.com/facebookresearch/mbrl-lib/blob/master/mbrl/models/gaussian_mlp.py#L256), and implemented [here](https://github.com/facebookresearch/mbrl-lib/blob/master/mbrl/models/gaussian_mlp.py#L162). This makes the code about 2X faster than the approaches I tried for sampling and indexing the models independently.

For testing iCEM you could use `BasicEnsemble` (see [example](https://github.com/facebookresearch/mbrl-lib/blob/master/mbrl/examples/conf/dynamics_model/basic_ensemble.yaml)), and also try it for control with ground truth dynamics (extending [this](https://github.com/facebookresearch/mbrl-lib/blob/master/mbrl/diagnostics/control_env.py) script).

For `GaussianMLP`, we could try adding an option to always round up population size to a multiple of the ensemble. If it performs similarly on our other tests, it might be a good compromise.

**Comment by sradicwebster** [comment]
Thanks for your reply. I've been a little busy, but have been able to put some more time to this.

I have done what you suggested for Gaussian MLP Ensemble and rounded the population size up to a multiple of the ensemble size. Running quick tests on cartpole shows better performance for a smaller population for iCEM vs CEM (although the runtime is longer). I have limited compute resources, so am unable to perform many experiments or do hyperparameter tuning. 

I have some issues running iCEM with the ground trust dynamics using the control_env script due to the multiprocessing, would you be able to have a look for me?

Is the best thing now for me to submit a pull request?

**Comment by luisenp** [comment]
Hi @sradicwebster. That's great! Yes, a pull request would be ideal. I can then take a look at the code, run your examples and do bigger tests.
